language: node_js
node_js:
  - "5.7"
install:
  - npm install
  - npm install sqlite3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - npm run test-karma
env:
  - CXX=g++-4.8 KARMA_BROWSER=Firefox
addons:
  firefox: "latest-beta"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
