language: node_js
node_js:
  - "6.9.1"
cache:
  directories:
    - node_modules
services:
  - postgresql
  - xvfb
install:
  - npm install
  - npm install pg
before_script:
  # set up for headless firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # change postgres user password
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
  # create database and schema
  - psql -c 'create database zappr;' -U postgres
  - psql -c 'create schema zappr_data; create schema zappr_meta;' -U postgres zappr
  # configure test db connection
  - export DB_HOST=localhost
  - export DB_PASSWORD="postgres"
script:
  - npm test
  - npm run test-karma
env:
  - CXX=g++-4.8 KARMA_BROWSER=Firefox
addons:
  postgresql: "9.4"
  firefox: "latest-beta"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
