# ZAPPR default configuration.
# All values can be overriden via commandline arguments
# or environment variables using the nconf module.

# IMPORTANT! Override secret with a secure value.
SESSION_SECRET: secret

# Override Github client id and secret with your
# own values as defined in your Github account.
GITHUB_CLIENT_ID: id
GITHUB_CLIENT_SECRET: secret
GITHUB_SCOPES:
  - user:email
  - public_repo
  - admin:repo_hook
GITHUB_HOOK_SECRET: foo
GITHUB_URL: https://api.github.com

# Address of the web application host
# that ZAPPR is going to run on.
HOST_ADDR: http://127.0.0.1:8080
APP_PORT: 3000
NODE_ENV: development
STATIC_DIR: ./dist/client

# Database configuration
# sqlite or postgres
DB_DRIVER: sqlite
#DB_NAME: postgres
#DB_USER: postgres
#DB_PASS: postgres
#DB_HOST: 192.168.99.100
#DB_PORT: 5432
#DB_SCHEMA: zappr
SQLITE_FILE: ./zappr.sqlite

# Token encryption
# Options: [~, kms]
ENCRYPTION_ENGINE: ~
# ENCRYPTION_KEY: arn:aws:kms:eu-west-1:082194939997:key/913dc389-7399-436d-94b8-16ed31d88be7
# KMS_REGION: eu-west-1

# HTTP logging
MORGAN_FORMAT: dev
MORGAN_THRESH: 0

# Zappr configuration
# ===================

# path to zapprfile in repository
ZAPPR_FILE_PATH: "/.zappr.yml"
ZAPPR_DEFAULT_CONFIG:
  approvals:
    minimum: 2
    pattern: "^:\\+1:$"
    # from:
    #   orgs:
    #     - zalando
    #   collaborators: true
    #   users:
    #     - prayerslayer
    #     - mfellner
